# Generated by Django 4.2.3 on 2023-07-28 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.UUIDField(default='678cd415d9de46598fed7f70f2bc21d1', unique=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='lobby_name',
            field=models.UUIDField(default=uuid.UUID('891afcbe-f5d6-499c-ac92-e517e24e4fa2'), unique=True),
        ),
    ]
