# Generated by Django 4.2.3 on 2023-07-28 11:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gameroom_creator_alter_gameroom_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='lobby_name',
            field=models.UUIDField(default=uuid.UUID('bb985786-9b22-4c99-80f4-9f1350b03f37'), unique=True),
        ),
    ]
