# Generated by Django 4.2.3 on 2023-07-28 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_gameroom_room_name_alter_lobby_lobby_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_name',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
