# Generated by Django 4.2.3 on 2023-07-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lobby_lobby_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'get_latest_by': '-id', 'ordering': ('-id',)},
        ),
    ]
