# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_gameroom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'get_latest_by': 'id', 'ordering': ('-id',)},
        ),
    ]
